<?xml version="1.0"?>
<package format="3">
  <name>navigation</name>
  <version>0.0.0</version>
  <description>Multi-AMR Nav2 launch files and navigation resources.</description>
  <maintainer email="rokeydg1@gmail.com">rokey</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>ament_index_python</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <exec_depend>nav2_bringup</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
